version: 0.2

phases:
  install:
    commands:
      - echo Installing Nginx...
      - sudo yum update -y
      - sudo amazon-linux-extras install nginx1 -y
      - sudo systemctl start nginx
      - sudo systemctl enable nginx

  build:
    commands:
      - echo Build started on `date`
      - sudo cp -r index.html /usr/share/nginx/html/

  post_build:
    commands:
      - echo Configuring Nginx to serve index.html...
      - sudo systemctl restart nginx

artifacts:
  files:
    - /usr/share/nginx/html/index.html

