version: 0.2

phases:
  install:
    commands:
      - echo Installing Nginx...
      - sudo yum update -y
      - sudo yum install nginx -y
      - sudo service nginx start 
      - sudo service nginx enable 

  build:
    commands:
      - echo Build started on `date`
      - sudo cp -r index.html /usr/share/nginx/html/

  post_build:
    commands:
      - echo Configuring Nginx to serve index.html...
      - sudo service nginx restart

artifacts:
  files:
    - /usr/share/nginx/html/index.html

